---
title: ""
author: "Tony Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

# Fix vax data

```{r}
left_join(
  here::here("data", "vax-data-old.csv") %>%
    read_csv(),
  here::here(
    "data",
    "COVID-19_Vaccinations_in_the_United_States_County.csv"
  ) %>%
    read_csv() %>%
    janitor::clean_names() %>%
    filter(date == "11/30/2021") %>%
    select(fips, series_complete_pop_pct),
  by = "fips"
) %>% 
  # mutate(series_complete_pop_pct.x = series_complete_pop_pct.y) %>% 
  rename(series_complete_pop_pct = series_complete_pop_pct.y) %>% 
  select(-series_complete_pop_pct.x) %>% 
  write_csv("data/vax-data.csv") %>% 
  filter(series_complete_pop_pct != 0) %>%
  ggplot() +
  aes(x = series_complete_pop_pct) +
  geom_histogram(binwidth = 1) %>%
  identity()
```

