---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r data, include=FALSE}
data <-
  here::here("data", "vax-data.csv") %>%
  read_csv(show_col_types = FALSE) %>% 
  filter(series_complete_pop_pct != 0) 
```

```{r model-1, include=FALSE}
model_1 <-
  data %>%
  lm(
    series_complete_pop_pct ~ stringency + county_level_index +
      I(stringency * county_level_index),
    .
  ) 

model_1_robust <-
  data %>%
  lm(
    series_complete_pop_pct ~ stringency + county_level_index +
      I(stringency * county_level_index),
    .
  ) %>%
  lmtest::coeftest(sandwich::vcovHC(., method = "white1", type = "HC1"))
```

```{r model-2, include=FALSE}
model_2 <-
  data %>%
  lm(
    series_complete_pop_pct ~ republican_percent +  county_level_index +
      I(republican_percent * county_level_index),
    .
  ) 

model_2_robust <-
  data %>%
  lm(
    series_complete_pop_pct ~ republican_percent +  county_level_index +
      I(republican_percent * county_level_index),
    .
  ) %>%
  lmtest::coeftest(sandwich::vcovHC(., method = "white1", type = "HC1"))
```

```{r model-3, include=FALSE}
model_3 <-
  data %>%
  lm(
    series_complete_pop_pct ~ stringency + county_level_index +
      I(stringency * county_level_index) +
      republican_percent + county_level_index +
      I(republican_percent * county_level_index),
    .
  ) 

model_3_robust <-
  data %>%
  lm(
    series_complete_pop_pct ~ stringency + county_level_index +
      I(stringency * county_level_index) +
      republican_percent + county_level_index +
      I(republican_percent * county_level_index),
    .
  ) %>%
  lmtest::coeftest(sandwich::vcovHC(., method = "white1", type = "HC1"))
```

```{r model-4, include=FALSE}
model_4 <-
  data %>%
  ivreg::ivreg(
    series_complete_pop_pct ~ stringency + county_level_index +
      I(stringency * county_level_index) +
      republican_percent + county_level_index +
      I(republican_percent * county_level_index) |
      county_level_index + median_household_income +
      percent_adults_with_ba + percent_in_fair_or_poor_health +
      percent_rural + percent_black + percent_65,
    data = .
  )  

model_4_roboust <-
  data %>%
  ivreg::ivreg(
    series_complete_pop_pct ~ stringency + county_level_index +
      I(stringency * county_level_index) +
      republican_percent + county_level_index +
      I(republican_percent * county_level_index) |
      county_level_index + median_household_income +
      percent_adults_with_ba + percent_in_fair_or_poor_health +
      percent_rural + percent_black + percent_65,
    data = .
  )  %>%
  lmtest::coeftest(sandwich::vcovHC(., method = "white1", type = "HC1"))
```

```{r add-lines-vectors, results='asis', echo=FALSE}
# lines to add to table
obs <- c("Observations", nobs(model_1), nobs(model_2), nobs(model_3), nobs(model_4))
r2 <- round(c(summary(model_1)$r.squared, summary(model_2)$r.squared, summary(model_3)$r.squared),3)
r2 <- c("R2", r2)
ar2 <- c(summary(model_1)$adj.r.squared, summary(model_2)$adj.r.squared, summary(model_3)$adj.r.squared) %>% 
  round(3)
ar2 <- c("Adjusted R2", ar2)
rse <- c(
  "Residual Std. Error",
  round(sigma(model_1),3),
  round(sigma(model_2),3),
  round(sigma(model_3),3),
  round(sigma(model_4),3)
  )
df_rse <- c(
  "df",
  model_1$df.residual,
  model_2$df.residual,
  model_3$df.residual,
  model_4$df.residual
)
f <- c(
  "F Statistic",
  paste0(round(summary(model_1)$fstat[1], 1), "***"),
  paste0(round(summary(model_2)$fstat[1], 1), "***"),
  paste0(round(summary(model_3)$fstat[1], 1), "***"),
  paste0(round(summary(model_4)$wald[1], 1), "***")
  
)
df_f <- c(
  "df",
  paste0(summary(model_1)$f[2], ", ", summary(model_1)$f[3]),
  paste0(summary(model_2)$f[2], ", ", summary(model_2)$f[3]),
  paste0(summary(model_3)$f[2], ", ", summary(model_3)$f[3]),
  paste0(summary(model_4)$wald[3], ", ", summary(model_4)$wald[4])
)
```

```{r table3, results='asis', echo=FALSE}
stargazer::stargazer(
  model_1_robust, model_2_robust, model_3_robust, model_4_roboust,
  # type = "html",
  add.lines = list(
    obs,
    r2,
    ar2, 
    rse,
    # df_rse,
    f
    # df_f
    
  ),
  intercept.bottom = FALSE,
  covariate.labels = c(
    "Constant",
    "Public Health",
    "Personal Freedom",
    "Social K",
    "Social K * Public Health",
    "Social K * Personal Freedom"
  ),
  title = "Regression Results",
  dep.var.labels = "Percentage of County Vaccinated",
  notes.label = "Standard errors are heteroskedasticity robust.",
  header = FALSE
)
  
```





