---
output: pdf_document
---

```{r setup-tab5, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r data-tab5, include=FALSE}
data <-
  here::here("data", "vax-data.csv") %>%
  read_csv(show_col_types = FALSE) %>% 
  filter(series_complete_pop_pct != 0) 
```

```{r model-1-tab5, include=FALSE}
model_1 <-
  data %>%
  lm(
    series_complete_pop_pct ~ stringency + 
      family_unity +
      community_health +
      institutional_health + 
      collective_efficacy +
      I(stringency * family_unity) + 
      I(stringency * community_health) + 
      I(stringency * institutional_health) +
      I(stringency * collective_efficacy),
    .
  )

model_1_robust <-
  model_1 %>%
  lmtest::coeftest(sandwich::vcovHC(., method = "white1", type = "HC1"))
```

```{r model-2-tab5, include=FALSE}
model_2 <-
  data %>%
  lm(
    series_complete_pop_pct ~ republican_percent + 
      family_unity +
      community_health +
      institutional_health + 
      collective_efficacy +
      I(republican_percent * family_unity) + 
      I(republican_percent * community_health) + 
      I(republican_percent * institutional_health) +
      I(republican_percent * collective_efficacy),
    .
  ) 


model_2_robust <-
  model_2 %>% 
  lmtest::coeftest(sandwich::vcovHC(., method = "white1", type = "HC1"))
```

```{r model-3-tab5, include=FALSE}
model_3 <-
  data %>%
  lm(
    series_complete_pop_pct ~ stringency + republican_percent +
      family_unity +
      community_health +
      institutional_health + 
      collective_efficacy +
      I(stringency * family_unity) + 
      I(stringency * community_health) + 
      I(stringency * institutional_health) +
      I(stringency * collective_efficacy) + 
      I(republican_percent * family_unity) + 
      I(republican_percent * community_health) + 
      I(republican_percent * institutional_health) +
      I(republican_percent * collective_efficacy),
    .
  ) 

model_3_robust <-
  model_3 %>% 
  lmtest::coeftest(sandwich::vcovHC(., method = "white1", type = "HC1"))
```


```{r add-lines-vectors-tab5, results='asis', echo=FALSE}
# lines to add to table
obs <- c("Observations", nobs(model_1), nobs(model_2), nobs(model_3))
r2 <- round(c(summary(model_1)$r.squared, summary(model_2)$r.squared, summary(model_3)$r.squared),3)
r2 <- c("R2", r2)
ar2 <- c(summary(model_1)$adj.r.squared, summary(model_2)$adj.r.squared, summary(model_3)$adj.r.squared) %>% 
  round(3)
ar2 <- c("Adjusted R2", ar2)
rse <- c(
  "Residual Std. Error",
  round(sigma(model_1),3),
  round(sigma(model_2),3),
  round(sigma(model_3),3)
  )
df_rse <- c(
  "df",
  model_1$df.residual,
  model_2$df.residual,
  model_3$df.residual
)
f <- c(
  "F Statistic",
  paste0(round(summary(model_1)$fstat[1], 1), "***"),
  paste0(round(summary(model_2)$fstat[1], 1), "***"),
  paste0(round(summary(model_3)$fstat[1], 1), "***")
  
)
df_f <- c(
  "df",
  paste0(summary(model_1)$f[2], ", ", summary(model_1)$f[3]),
  paste0(summary(model_2)$f[2], ", ", summary(model_2)$f[3]),
  paste0(summary(model_3)$f[2], ", ", summary(model_3)$f[3])
)
```

```{r table5, results='asis', echo=FALSE}
stargazer::stargazer(
  model_1_robust,
  model_2_robust,
  model_3_robust,
  # type = "html",
  add.lines = list(obs,
                   r2,
                   f),
  intercept.bottom = FALSE,
  covariate.labels = c(
    "Constant",
    "Public Health",
    "Personal Freedom",
    "Family Unit",
    "Community Health",
    "Institutional Health",
    "Collective Efficacy",
    "Family Unit * Public Health",
    "Community Health * Public Health",
    "Institutional Health * Public Health",
    "Collective Efficacy * Public Health",
    "Family Unit * Personal Freedom",
    "Community Health * Personal Freedom",
    "Institutional Health * Personal Freedom",
    "Collective Efficacy * Personal Freedom"
  ),
  title = "Regression Results",
  dep.var.labels = "Percentage of County Vaccinated",
  notes.label = "Standard errors are heteroskedasticity robust.",
  header = FALSE
)

  
```





