---
output: pdf_document
---

```{r setup-tab2, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r data-tab2}
df <-
  here::here("data", "vax-data.csv") %>%
  read_csv(show_col_types = FALSE) %>% 
  filter(series_complete_pop_pct != 0) %>% 
  select(
    series_complete_pop_pct,
    contains("days"),
    -days,
    stringency,
    county_level_index,
    republican_percent,
    percent_adults_with_ba,
    percent_in_fair_or_poor_health,
    percent_black,
    percent_rural,
    percent_65,
    median_household_income
  ) %>%
  as.data.frame()
```

```{r tab2, results = 'asis'}
df %>%
  stargazer::stargazer(
    type = "latex",
    summary.stat = c("n",
                     "min",
                     "max",
                     "mean",
                     "median",
                     "sd"),
    digits = 2,
    covariate.labels = c(
      "\\% Vaccinated",
      "Bar Days",
      "Gathering Days",
      "Mask Days",
      "Restaurant Days",
      "Stay at Home Days",
      "Stringency",
      "County Level Index",
      "\\% Republican",
      "\\% Bachelor's",
      "\\% Fair/Poor Health",
      "\\% Black",
      "\\% Rural",
      "\\% > 65",
      "Median Household Income"
    )
  )
```



